### ISSUE TITLE
Missing asahi-bless package in the channel

### ISSUE THREAD

**Issue by ghost** [asahi-guix/channel#4]
Currently, there's no easy way to switch the default volume from within a guix install. Having access to the asahi-bless package would allow for that.

**Comment by r0man** [comment]
Hi @ytane,

I added the other packages from the asahi-nvram repository, but haven't tested them.
I think a new release of eudev is needed to include https://github.com/eudev-project/eudev/blob/master/rules/60-persistent-storage-mtd.rules or those rules need to be provided manually.

**Comment by ghost** [comment]
Tried the rust-asahi-bless package and I get the following error when executing it.

Error: Failed to read nvram contents, try running with sudo? Inner error: Os { code: 2, kind: NotFound, message: "No such file or directory" }

**Comment by r0man** [comment]
@ytane I also got that far, but I think those devices are missing because of the udev rules I mentioned above. I think they have to either be added manually (which I haven tried yet), or they will eventually appear with the next eudev release.

**Comment by ghost** [comment]
Yes, seems like it. The asahi-bless binary tries to access "/dev/mtd/by-name/nvram" which doesn't exist.

Though, I did have it working on guix with a package on my personal channel. It seems asahi-bless started using the mtd devices by name from version 0.4.1 in this [commit](https://github.com/WhatAmISupposedToPutHere/asahi-nvram/commit/6c344e2234dd19f14da38f0492b9216265da5f56). Before that, on 0.4.0, they used mtd0 directly, which works on guix.

**Comment by r0man** [comment]
Hi @ytane, I changed the version of rust-asahi-bless-0.4: for now back to 0.4.0.

**Comment by ghost** [comment]
I tested this, & 0.4.0 works now. Thanks.

```
 1) macOS
 2) Asahi
*3) Guix

Enter a number to select a boot volume:
==> 1
```

**Comment by r0man** [comment]
Nice, thanks for confirming!
