### ISSUE TITLE
llvmpipe being used instead of the asahi mesa driver

### ISSUE THREAD

**Issue by ghost** [asahi-guix/channel#6]
Executing glxinfo from the asahi-mesa-utils package gives the following output in my guix installation.

```
OpenGL vendor string: Mesa
OpenGL renderer string: llvmpipe (LLVM 18.1.8, 128 bits)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 25.0.0-devel
```

It seems to be using the llvmpipe (Software rendering) driver instead of the asahi one even when using the asahi-mesa package. Is there some kernel argument or environment variable that needs to be set, to use the asahi driver?

**Comment by ghost** [comment]
I hadn't enabled the modesetting configuration in xorg-configuration.

**Comment by r0man** [comment]
Hi @ytane,

I think you have to make sure the packages you install actually use asahi-mesa, and not the mesa from Guix. To do that you can use the `replace-asahi` function from the `(asahi guix transformations)` module, or do it yourself.

The system definitions in the asahi-guix channel do this here:
- https://github.com/asahi-guix/channel/blob/8cd8fcf0d2500e35c4d69f97a4b7a8ea65c37533/modules/asahi/guix/systems/desktop.scm#L67
- https://github.com/asahi-guix/channel/blob/8cd8fcf0d2500e35c4d69f97a4b7a8ea65c37533/modules/asahi/guix/systems/sway.scm#L33

I also do this in my personal config here:
- https://github.com/r0man/guix-home/blob/c13037c882f11f883dc0ccc99bd8d2224dd3d9f1/modules/r0man/guix/system/m1.scm#L68

You probably want to replace `alsa-ucm-conf` as well to get audio working.

I'm not sure if this is the best way. If you know a better approach, please let me know.

I hope that helps.

**Comment by ghost** [comment]
Yes, I had that configured using the options->transformation procedure. Just hadn't enabled the modeset config, so asahi driver wasn't being used at all.

```
(options->transformation
    '((with-input . "wireplumber=asahi-wireplumber")
      (with-input . "pipewire=asahi-pipewire")
      (with-input . "mesa-utils=asahi-mesa-utils")
      (with-input . "mesa-headers=asahi-mesa-headers")
      (with-input . "alsa-ucm-conf=asahi-alsa-ucm-conf")
      (with-input . "alsa-lib=asahi-alsa-lib")
      (with-input . "mesa=asahi-mesa")))
```

Saw the 30-modeset.conf in the debian asahi docs & found it here as well, so I added it to my config and asahi driver is working now. Thanks for the help.
